services:
  db:
    image: postgres:17
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  cache:
    image: redis:8
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - redis_data:/data
    
  broker:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    
  worker:
    build: ./backend
    container_name: celery
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: celery -A src.celery.celery_app worker --loglevel=info
    depends_on:
      - broker

  backend:
    build: ./backend
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: bash entrypoint.sh
    depends_on:
      - db
      - cache
      - worker

volumes:
  postgres_data:
  redis_data: